// Section names - expandable without code changes
export const SECTIONS = {
  BRANCHES: "الفروع",
  WAREHOUSES: "المخازن", 
  TRIPS: "الرحلات",
  PRINT:"الطباعة",
  EMPLOYEES: "الموظفين",
  PILGRIMS: "الحجاج",
  SUPPLIES: "التوريدات",
  TICKETS: "التذاكر",
  INVOICES: "الفواتير",
  REPORTS: "التقارير",
  SETTINGS: "الإعدادات",
  HR: "الموارد البشرية",
  BUS_DRIVERS: "سائقين الحافلات",
  HOTELS: "الفنادق",
  PRODUCTS: "المنتجات",
  LOYALTY: "الولاء"
};

// Permission levels
export const PERMISSIONS = {
  NONE: "none",
  VIEW: "view", 
  EDIT: "edit",
  ADMIN: "admin"
};

// Default roles with their permissions
export const DEFAULT_ROLES = {
  SUPER_ADMIN: {
    roleName: "super_admin",
    displayName: "مدير عام",
    permissions: {
      [SECTIONS.BRANCHES]: PERMISSIONS.ADMIN,
      [SECTIONS.WAREHOUSES]: PERMISSIONS.ADMIN,
      [SECTIONS.TRIPS]: PERMISSIONS.ADMIN,
      [SECTIONS.EMPLOYEES]: PERMISSIONS.ADMIN,
      [SECTIONS.PILGRIMS]: PERMISSIONS.ADMIN,
      [SECTIONS.SUPPLIES]: PERMISSIONS.ADMIN,
      [SECTIONS.TICKETS]: PERMISSIONS.ADMIN,
      [SECTIONS.INVOICES]: PERMISSIONS.ADMIN,
      [SECTIONS.REPORTS]: PERMISSIONS.ADMIN,
      [SECTIONS.SETTINGS]: PERMISSIONS.ADMIN,
      [SECTIONS.HR]: PERMISSIONS.ADMIN,
      [SECTIONS.BUS_DRIVERS]: PERMISSIONS.ADMIN,
      [SECTIONS.HOTELS]: PERMISSIONS.ADMIN,
      [SECTIONS.PRODUCTS]: PERMISSIONS.ADMIN,
      [SECTIONS.LOYALTY]: PERMISSIONS.ADMIN
    }
  },
  BRANCH_ADMIN: {
    roleName: "branch_admin",
    displayName: "مدير فرع",
    permissions: {
      [SECTIONS.BRANCHES]: PERMISSIONS.VIEW,
      [SECTIONS.WAREHOUSES]: PERMISSIONS.EDIT,
      [SECTIONS.TRIPS]: PERMISSIONS.EDIT,
      [SECTIONS.EMPLOYEES]: PERMISSIONS.VIEW,
      [SECTIONS.PILGRIMS]: PERMISSIONS.EDIT,
      [SECTIONS.SUPPLIES]: PERMISSIONS.EDIT,
      [SECTIONS.TICKETS]: PERMISSIONS.EDIT,
      [SECTIONS.INVOICES]: PERMISSIONS.EDIT,
      [SECTIONS.REPORTS]: PERMISSIONS.VIEW,
      [SECTIONS.SETTINGS]: PERMISSIONS.NONE,
      [SECTIONS.HR]: PERMISSIONS.NONE,
      [SECTIONS.BUS_DRIVERS]: PERMISSIONS.VIEW,
      [SECTIONS.HOTELS]: PERMISSIONS.VIEW,
      [SECTIONS.PRODUCTS]: PERMISSIONS.VIEW,
      [SECTIONS.LOYALTY]: PERMISSIONS.VIEW
    }
  },
  REP: {
    roleName: "rep",
    displayName: "مندوب",
    permissions: {
      [SECTIONS.BRANCHES]: PERMISSIONS.NONE,
      [SECTIONS.WAREHOUSES]: PERMISSIONS.NONE,
      [SECTIONS.TRIPS]: PERMISSIONS.VIEW,
      [SECTIONS.EMPLOYEES]: PERMISSIONS.NONE,
      [SECTIONS.PILGRIMS]: PERMISSIONS.EDIT,
      [SECTIONS.SUPPLIES]: PERMISSIONS.VIEW,
      [SECTIONS.TICKETS]: PERMISSIONS.EDIT,
      [SECTIONS.INVOICES]: PERMISSIONS.VIEW,
      [SECTIONS.REPORTS]: PERMISSIONS.NONE,
      [SECTIONS.SETTINGS]: PERMISSIONS.NONE,
      [SECTIONS.HR]: PERMISSIONS.NONE,
      [SECTIONS.BUS_DRIVERS]: PERMISSIONS.NONE,
      [SECTIONS.HOTELS]: PERMISSIONS.NONE,
      [SECTIONS.PRODUCTS]: PERMISSIONS.NONE,
      [SECTIONS.LOYALTY]: PERMISSIONS.NONE
    }
  },
  ACCOUNTANT: {
    roleName: "accountant",
    displayName: "محاسب",
    permissions: {
      [SECTIONS.BRANCHES]: PERMISSIONS.NONE,
      [SECTIONS.WAREHOUSES]: PERMISSIONS.NONE,
      [SECTIONS.TRIPS]: PERMISSIONS.NONE,
      [SECTIONS.EMPLOYEES]: PERMISSIONS.NONE,
      [SECTIONS.PILGRIMS]: PERMISSIONS.VIEW,
      [SECTIONS.SUPPLIES]: PERMISSIONS.VIEW,
      [SECTIONS.TICKETS]: PERMISSIONS.VIEW,
      [SECTIONS.INVOICES]: PERMISSIONS.ADMIN,
      [SECTIONS.REPORTS]: PERMISSIONS.VIEW,
      [SECTIONS.SETTINGS]: PERMISSIONS.NONE,
      [SECTIONS.HR]: PERMISSIONS.NONE,
      [SECTIONS.BUS_DRIVERS]: PERMISSIONS.NONE,
      [SECTIONS.HOTELS]: PERMISSIONS.NONE,
      [SECTIONS.PRODUCTS]: PERMISSIONS.NONE,
      [SECTIONS.LOYALTY]: PERMISSIONS.NONE
    }
  }
}; 